title: 分享经验 共同成长
description: My Personal Stack Problems
author: 取乎其上
github: https://leexiaofang.github.io
about: 深入理解基本概念 提升实际开发效率
disqus_shortname: 所有文章
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://leexiaofang.github.io"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: 自我介绍
      url: /about/
    - text: 我的项目
      url: /projects/

url: "https://leexiaofang.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
